### ISSUE TITLE
Cannot add CMS content into a Commerce ContentArea 

### ISSUE THREAD

**Issue by heinzmuller** [episerver/netcore-preview#102]
Hi, we have some issues with ContentArea's for Commerce content.

In previous Episerver versions there is a "Browse existing content" button that enables the editor to add CMS content, this does not appear in the new Commerce versions for us.

Episerver 12
![Screenshot 2021-07-02 at 13 00 09](https://user-images.githubusercontent.com/1785105/124265546-1ca19300-db36-11eb-9085-047b61013a7f.png)
![Screenshot 2021-07-02 at 13 05 47](https://user-images.githubusercontent.com/1785105/124265649-45c22380-db36-11eb-8402-d77b821512c3.png)

Episerver 11
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1785105/124265518-11e6fe00-db36-11eb-97e1-d1c1b6bccdfb.png)

**Comment by barteksekula** [comment]
"Browse existing content" was a part of EPiServer Labs - Block Enhancements https://github.com/episerver/EPiServer.Labs.BlockEnhancements#contentareasettings
This Labs package has not been migrated to netcore yet.

**Comment by heinzmuller** [comment]
That means there is currently no way to add CMS content into a Commerce ContentArea until this enhancement is updated?

**Comment by barteksekula** [comment]
You can still use Drag & Drop from the Assets pane right?

**Comment by heinzmuller** [comment]
I can add blocks as they are present in the assets pane, but I cannot add any pages (like ArticlePage's in this instance)

**Comment by barteksekula** [comment]
You're right, I forgot about pages.
So this won't be available until we migrate the Labs package

**Comment by heinzmuller** [comment]
Isn't this a major oversight that you cannot add content without this extension? :)

**Comment by barteksekula** [comment]
This was never possible without the `Labs` package. I think that eventually we will migrate all our products to netcore but this will take some time.

**Comment by lunchin** [comment]
I added the following issue in feedback.  Please vote on the issue there, and we will try to get prioritized.  Closing this one since the other issue is now open.
https://feedback.episerver.com/ideas/COM-I-96
