### ISSUE TITLE
Commerce: Carts cannot be deleted in Order Management

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#103]
**Observations:**
In Order Management, when viewing a shopping cart, there is no option to delete a cart. In the old Commerce Manager, this was possible and very useful.

**Expected:**
A button to delete one or more carts is expected in such an order management tool.

**Builds:**
- EPiServer.CMS.UI.Core: 12.0.0-pre-021601
- EPiServer.Commerce: 14.0.0-inte-021024

**Comment by lunchin** [comment]
Added to internal tracker

**Comment by lunchin** [comment]
This has been prioritized to come after GA, so should not have to wait long without the feature.
