### ISSUE TITLE
Synchronizing models when startup, no CultureSpecific  to CultureSpecific properties

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#104]
If you have a property that is global and has a value and you change it to be CultureSpecific the admin interface reports that the property is Localized = Yes. In edit the property still have values on language branches. If you remove the value and publish the page the property value will still be there after the reload of the page. 

If you go to admin and choose "Revert to default" on the property then the behaviour is correct. When removing the property value and publish, the value is gone. 

Do you need to do "Revert to default" to get this behaviour or should the startup synchronizing fix this? 

@lunchin @jbearfoot @barteksekula

**Comment by lunchin** [comment]
Not sure I understand the issue
