### ISSUE TITLE
Scheduled job - duration

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#105]
My job reports 41min 29s but it has run for several hours (more than 5-6 hours). Are the hours missing or is there a bug in the duration report time?

![image](https://user-images.githubusercontent.com/106393/124821793-6bed2680-df6f-11eb-91a8-1a7e71c9cee8.png)

@barteksekula

**Comment by lunchin** [comment]
Added to internal tracker

**Comment by lunchin** [comment]
Fixed in EPiServer.CMS.UI.Admin.12.0.1-pre-022064
