### ISSUE TITLE
Admin mode: Manage content is missing

### ISSUE THREAD

**Issue by tomahg** [episerver/netcore-preview#107]
The removal of «Manage Content» is not good! It is not used only for managing access rights, but also as an editing interface for content that is not Pages/Blocks/Media but inherits ContentData (or simply implements IContent). If «Manage Content» is removed, customers that store custom objects as IContent need another way to edit those.

**Comment by lunchin** [comment]
I think that is a valid use case but not sure would like to manage content in the way it was in admin mode.  It is something we will look to bring back in some form after GA

**Comment by lunchin** [comment]
This has been prioritized to come after GA, so should not have to wait long without the feature.
