### ISSUE TITLE
Admin mode: Convert pages is missing

### ISSUE THREAD

**Issue by tomahg** [episerver/netcore-preview#108]
«Convert Pages» is very useful, and I'm surprised it's removed, as all the converting is done in SQL - all that's needed is rewriting the frontend. Adding support for converting blocks should also be easy, as explained in this blog post: https://www.gulla.net/en/blog/convert-episerver-blocks/

**Comment by lunchin** [comment]
Yes is something we want to bring back but deprioritized until after GA since we also wanted to introduce new functionality as supporting blocks like you mentiioned.

**Comment by lunchin** [comment]
This has been prioritized to come after GA, so should not have to wait long without the feature.
