### ISSUE TITLE
AspNet Identity: Any chance to jump on v3 for Microsoft.Data.SqlClient?

### ISSUE THREAD

**Issue by valdisiljuconoks** [episerver/netcore-preview#111]
Hi,

Any chance to jump on `>= 3.0` version for `Microsoft.Data.SqlClient` inside `EPiServer.CMS.UI.AspNetIdentity` package before the release?

**Comment by lunchin** [comment]
Will look into upgrading the dependency

**Comment by lunchin** [comment]
Fixed 12.0.1
