### ISSUE TITLE
Deleting a page with many subpages fails and no delete is done

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#112]
By selecting "move to trash" for a page with lots of sub pages the reference pages check returns 200 and UI shows Trash but no delete is done.  To delete these pages we need to use the stored procedure EXEC editDeleteChilds and restart the instance in the paas portal.

![image](https://user-images.githubusercontent.com/106393/128999411-a63d828f-a12e-4e88-b142-548e078f8325.png)

We are running on Episerver.CMS.UI.Core 12.0.0-pre-021601 (not the latest). 

@barteksekula

**Comment by barteksekula** [comment]
@oyvindwh do you still have that workaround from https://github.com/episerver/netcore-preview/issues/97#issuecomment-897533932 ?

**Comment by oyvindwh** [comment]
Yes we do.

We are updating on Monday to the latest packages, can update the ticket then if this could be solved in the latest.
