### ISSUE TITLE
Export and Manage Websites does not allow you to select subpages from level 1

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#114]
I want to export one page in the page structure lower in the structure. I can not open the content items to get lower in the structure.

![image](https://user-images.githubusercontent.com/106393/129896217-2abbfab7-68e5-4c27-a24e-41e5c73b71f9.png)

Same problem when Manage Websites but I guess they are using the same react component. 

@barteksekula @lunchin

**Comment by haugsten** [comment]
Same problem for "Set Access Rights"

**Comment by barteksekula** [comment]
It's already fixed in the newest package which will be pushed shortly.

**Comment by lunchin** [comment]
Fixed in 12.0.1
