### ISSUE TITLE
Find: Manage page crashes on load

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#117]
When viewing the Manage page of Episerver Find, the page fails (the "Something went wrong" modal box shows up).
Upon inspecting the network trace, it seems `/EPiServer/Find/bestbets/` always returns 404.

Builds:
- EPiServer.Find.UI.Core: 14.0.0-inte-020240

**Comment by lunchin** [comment]
I just added the latest to the feed.

**Comment by lunchin** [comment]
closing this cannot recreate
