### ISSUE TITLE
My settings - Display Options is throwing an exception

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#118]
/EPiServer/EPiServer.Cms.UI.Settings/settings?parentProduct=global_cms

![image](https://user-images.githubusercontent.com/106393/131820110-eabd1f5b-d88e-44d2-84bc-f890f0df4ddb.png)

We are using AD login.

Will Reset View be available in CMS 12?

@barteksekula

**Comment by lunchin** [comment]
Added to internal tracker

**Comment by barteksekula** [comment]
Fixed in 12.0.2
