### ISSUE TITLE
Creating new jobs and changing guid does not create new job in admin

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#119]
We have created our own EmptyWastebasketJob, copied code from existing Episerver built in job. We updated the guid with new guid and started the job in admin. The name of the job was set by the LanguagePath = "/admin/databasejob/wastebasket" attribute. We removed the attribute and changed the DisplayName, but the job had still the translated name. We removed all attributes except for guid, DisplayName and gave the job a new guid. The result is no new job registered, just the  same job with the same name.

![image](https://user-images.githubusercontent.com/106393/131958583-fa4e9216-fa64-46ff-9c15-1430cedc45f5.png)

![image](https://user-images.githubusercontent.com/106393/131959083-1d2a5e76-e5e3-4017-b4ee-3ba5a29376ae.png)

By changing the class name and new guid we got a new job and our DisplayName correct. 

![image](https://user-images.githubusercontent.com/106393/131959578-b89a6e15-bc14-4a89-b8dc-35405220eac5.png)

Should not the guid be the key to do these changes?

**Comment by lunchin** [comment]
Added to internal tracker

**Comment by bjuris** [comment]
CMS-20109
