### ISSUE TITLE
Recycle Bin / Trash shows empty result even though items has been deleted

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#120]
When we delete a page it appears in the admin - access right, but when opening trash in edit mode the result is empty

We have an empty recycle bin when starting:

![image](https://user-images.githubusercontent.com/106393/131960370-07bdc861-e3f6-47b6-93b1-3c0c9d58e723.png)

Then we delete one (1) page and CatalogContent appears in the list:

![image](https://user-images.githubusercontent.com/106393/131960396-eef85832-fc9d-4a13-b80d-e6f0eed57e0c.png)

Trash returns empty result

![image](https://user-images.githubusercontent.com/106393/131960592-fa97b93f-6c8e-4fb7-b240-73d67ab1452a.png)

This returns empty result:
https://localhost:44376/EPiServer/cms/Stores/contentstructure/?referenceId=2&query=getchildren&allLanguages=true&isSearchable=true&dojo.preventCache=1630650410141

Everyone has access to the Recycle Bin. 

Is the CatalogContent messing up with a id = -1 ?

@jbearfoot

**Comment by lunchin** [comment]
added to internal tracker

**Comment by mrahl** [comment]
@oyvindwh does your user have _edit_ access to the recycle bin and the page in the recycle bin? Read access is not sufficient to see items in the recycle bin.

**Comment by oyvindwh** [comment]
User needs change access to the recycle bin. Thanks.

@haugsten
