### ISSUE TITLE
Content Area and links to pages in another language

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#122]
In the .net version of content area when you drag a page in another language (that is not translated) to the content area the item is grey + italic + the language code for the page. Like this:

![image](https://user-images.githubusercontent.com/106393/132388803-4f9f9045-9d5d-4f28-ab8c-6c347a34cb2d.png)

If you do the same in the .net core version the page does not get these attributes so the editor can not see that it is not translated to the selected language. Like this:

![image](https://user-images.githubusercontent.com/106393/132388409-ac90fc72-58ed-45c1-a3b1-ebf336efd3e5.png)

@barteksekula

**Comment by lunchin** [comment]
Added to internal tracker

**Comment by barteksekula** [comment]
@oyvindwh that is not part of the core CMS UI but a part of the Labs package https://github.com/episerver/EPiServer.Labs.BlockEnhancements#showing-block-status-on-content-area
Labs were not migrated to netcore yet.
