### ISSUE TITLE
Image Editor - save a copy of the image

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#123]
A better editor experience would be to fill in the filename with existing name + "-2" or the pre-set / size that is cropped / resized as a default in the file name text box.

![image](https://user-images.githubusercontent.com/106393/132907658-52624a60-279c-4f9b-97ef-e7134359a63d.png)

The filename is not available for copy when you have the save dialog window open.

**For even better editor experience:**
If you do not crop / resize the image (just and clicks ok the Image Editor closes but no message is given. Perhaps the OK button should be greyed out until a change is done? Easy to forget to press Apply button and just choose OK and then editors have to restart the action. 

![image](https://user-images.githubusercontent.com/106393/132908202-b33ae4f2-af8e-49cf-8a6c-dc79b707bcc6.png)

**Comment by barteksekula** [comment]
reported in our internal tracker
