### ISSUE TITLE
Image Editor - crop / resize does not work if you zoom in

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#124]
If you have a large image that is larger than the preview area in the editor and wants to crop / resize this image the behaviour is to zoom out and make the crop. The problem is that if you zoom out the pre-set will not work since the file information (width / height) is set to the percentage of the image and you will get an error.

![image](https://user-images.githubusercontent.com/106393/132909236-d90fc6c5-d1c2-45af-84bf-36b048877ee7.png)

In this case I selected pre-set 640*480 and the image full size is 1393*928 so a crop should be possible.
![image](https://user-images.githubusercontent.com/106393/132909330-dbf9dcf5-7ac8-4fa9-8336-846d025d67df.png)

@barteksekula

**Comment by barteksekula** [comment]
reported in our internal tracker
