### ISSUE TITLE
netcore-preview Alloy view componets are not compatible with EPiServer.Cms.AspNetCore.Mvc, Version=12.0.3.0

### ISSUE THREAD

**Issue by alasvant** [episerver/netcore-preview#125]
The current Alloy view components (2021-09-12 preview sources) are not compatible with the EPiServer.Cms.AspNetCore.Mvc, Version=12.0.3.0

There is a breaking change in 12.0.2.0 to 12.0.3.0 version for the `PartialContentComponent<TContentData>` abstract class.
- it used to be that inheriting implementation would override the Invoke method like this: `public override IViewComponentResult Invoke(xxx)`
- now in version 12.0.3.0 the PartialContentComponent<TContentData> has been changed to have `public IViewComponentResult Invoke(TContentData currentContent)` method that will call the `protected abstract IViewComponentResult InvokeComponent(TContentData currentContent)` which inheritors need to override

So, when updating  the preview to use EPiServer.Cms.AspNetCore.Mvc, Version=12.0.3.0 one needs to change the following view components:
- PageListBlockViewComponent
- ImageFileViewComponent
- ContactBlockViewComponent
Fix: change: `public override IViewComponentResult Invoke(xxx)` signature to `protected override IViewComponentResult InvokeComponent(xxx)`

AlloyMvcTemplates.csproj

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\dependencies.props" />
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="$(BuildBundlerMinifier)" />
    <PackageReference Include="Wangkanai.Detection" Version="2.0.1" />
    <PackageReference Include="EPiServer.CMS" Version="$(CmsUIVersion)" />
    <PackageReference Include="EPiServer.CMS.AspNetCore.HtmlHelpers" Version="12.0.3" />
    <PackageReference Include="EPiServer.Hosting" Version="12.0.3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\LanguageFiles\**\*" />
  </ItemGroup>
  <ItemGroup>
    <None Include="wwwroot\**\*.*" />
  </ItemGroup>
</Project>
```

dependecies.props

```
<Project>
  <PropertyGroup>
    <CmsCoreVersion>12.0.2</CmsCoreVersion>
    <CmsUIVersion>12.0.2-pre-022337</CmsUIVersion>
    <TelemetryVersion>2.0.0</TelemetryVersion>
    <CommerceCoreVersion>14.0.2-pre-021330</CommerceCoreVersion>
    <CommerceTrackingeVersion>4.0.2-pre-021330</CommerceTrackingeVersion>
    <SerilogVersion>2.10.0</SerilogVersion>
    <SerilogAspNetCoreVersion>3.4.0</SerilogAspNetCoreVersion>
    <SerilogSinkFileVersion>4.1.0</SerilogSinkFileVersion>
    <NewtonsoftVersion>12.0.3</NewtonsoftVersion>
    <BuildBundlerMinifier>3.2.449</BuildBundlerMinifier>
  </PropertyGroup>
</Project>
```

**Comment by barteksekula** [comment]
reported in our internal tracker

**Comment by mrahl** [comment]
Thanks for reporting. We were aware of this, but the plan is to not include the alloy template in the public release so we havent prioritized updating it.

**Comment by alasvant** [comment]
@mrahl tes was aware that "Alloy" is not going to be part of the public release, just the same old demo site.

Do you want this kind of updates as contributions to Alloy or do you want to handle those from Optimizely side as you see fit? Same like Alloy still contains code that still uses concrete classes instead of interfaces, so those could be cleaned up by contributions, etc tidying of Alloy code ? Or should this repo be only now be used to test features and report issues directly related to the CMS/Commerce, edit and admin view functionality (meaning not the code in the Alloy)?

**Comment by mrahl** [comment]
@alasvant the future of alloy is uncertain. As you mention it has some patterns that aren't great, it is also based on by now very old components and practices in some places. Attention has definitely switched towards Foundation, though admittedly it serves a different purpose. We're definitely open for feedback - do you think there is a need for Alloy going forward?

Feel free to report any issue in here, especially during the preview period. With that soon coming to an end we will ramp down activity in this repo and go back to the more normal channels (support tickets, feedback portal etc).

**Comment by valdisiljuconoks** [comment]
Alloy is great for quick testing and sandboxing, not so great for foundation of your project.

**Comment by alasvant** [comment]
I totally agree with @valdisiljuconoks - Alloy is good for quick demos, if you want to quickly test an idea, etc but definitely not a foundation for a new production project ;) (one can pick ideas though)

So I guess at the moment there is Alloy to demo CMS, Quicksilver to demo commerce and Foundation to demo cms&commerce (more commerce ;P) and bunch of other features - so understandable why would Optimizely want to have three different solutions to maintain (+ all the other old demo sites :D).

I would suggest that you keep Alloy and Foundation - Alloy for quick demos, maybe not so up to date, but could be with community support (maybe something like what https://github.com/episerver/AlloyDemoKit is/was?).

**Comment by mrahl** [comment]
@alasvant @valdisiljuconoks thank you for your feedback!

**Comment by lunchin** [comment]
fixed
