### ISSUE TITLE
Admin view, tools -> change log, entrys data not fully visible

### ISSUE THREAD

**Issue by alasvant** [episerver/netcore-preview#127]
If a change log entry has long text for data field, that is not visible unless the "thing" that has created the message adds HTML BR-elements to the message (so creating very short lines). It really can't be like that, the UI should properly render the content of the log entrys data and show it all, because otherwise it is useless information for the users as they can't see the full message.

How to re-produce:
- log a long text to change log without using BR-elements in the message
- go to admin view -> tools -> change log
- read the log messages
- long text would be expected to be visible, but it is not (user can scroll a bit the element, but still can't see the full message)

expected: the log message is properly wrapped to the ares we have available in the UI, to see the full log message.

This message should be visible to the user without scrolling or inspecting the HTML ;)

![change-log-message-truncated](https://user-images.githubusercontent.com/22050586/132977548-ba5aa443-c2c6-4cfa-87e3-c49eb88c1a1d.PNG)

Adding BR-elements to the log message, we can make it visible at the moment, but that really is not an option as the thing logging cannot really know or care how the UI is going to display the message.

![change-log-message-truncated-2](https://user-images.githubusercontent.com/22050586/132977668-fb5e3811-401b-4ece-8082-0e4a9b241d15.PNG)

**Comment by barteksekula** [comment]
reported in our internal tracker

**Comment by bjuris** [comment]
CMS-20154
