### ISSUE TITLE
CMS: Scheduled job cannot be re-run if it was running during a site shutdown/restart

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#134]
**Observed**
If a scheduled job is running, and either the job crashes or the site is stopped/restarted, then the scheduled job cannot be started nor stopped from the Admin UI. It is simply stuck in a running state, without actually running (because the database says it is already running).

I have found that In order to run this job again, I can find the job in the database table tblScheduledItem and set its IsRunning value to false. Then the job buttons change in the Admin UI, and I can start the job again.

**Expected**
In the old Admin UI, I would be able to click Start, even when the job was already running. It would detect that the job was not actually running and allow it to be started.

**Builds**
- EPiServer.CMS.UI.Core: 12.0.2-pre-022463

**Comment by lunchin** [comment]
Added to internal tracker
