### ISSUE TITLE
LuceneSearchProvider: Path to search index in App_Data always use windows path

### ISSUE THREAD

**Issue by Mmmattias** [episerver/netcore-preview#135]
On MacOS, when running the full indexing scheduled job, the following files are created:

<Project root>/App_Data/SearchIndex\ECApplication\catalog blobs

The Windows style backslash in the path breaks the application that after this can no longer be started until the folder structure is removed.

**Comment by lunchin** [comment]
reported to internal tracker

**Comment by lunchin** [comment]
This should be fixed in 14.0.3, which should be on the feed next Tuesday
