### ISSUE TITLE
Modification of the ContentApiModel

### ISSUE THREAD

**Issue by jtonvang** [episerver/netcore-preview#138]
We've used the previous version of the Content Delivery API to make several SPAs - in every one of them, we extended the ContentModelMapper to be able to populate the ContentApiModel with additional properties , much like you'd do with a viewmodel in plain MVC. 
To accomplish this, we made a small framework that would let you create a small class, called a "processor" for each content type you'd like to process - and our extended ContentModelMapper would then resolve what processors was applicable for the content being served and apply those. Simple stuff, really. 
In version 3.0, I see that the ContentModelMapper is gone and I'm at a bit of a loss to understand what is meant to replace it. 

At first glance, it seemed like we could create an implementation of IContentFilter for each content type (much like we did before) and add properties that way, but properties added that way needs to be of the PropertyData-type, not ideal. 
Then you have the IContentApiModelFilter, but that isn't type specific in the same way and would require an additional lookup, making it feel a bit hacky. Not to mention that it is in the nature of a filter to remove stuff, not add it, so it kind of feels like we'd be misusing the API to begin with. 

My other idea was to extend the ContentConvertingService to allow us to allow us to have our own logic for something like an "IContentApiModelAppender" which is what we want. The class has virtual methods and extending it would be straight forward, but as it doesn't use an interface (why?), we can't replace the implementation, short of run-time-patching which seems like the worst of all options.

Could anyone shed a little light on what is the correct approach for what we're trying to accomplish?

**Comment by JohanPetersson** [comment]
If I understand you correctly, you could implement this in `IContentApiModelFilter`. You can access the content type from `ContentApiModel.ContentType.First()` and then determine which "processor" to run. The name "filter" doesn't imply that you can only remove things, think of it as filters in MVC, I guess this would be the most equivalent https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0#result-filters. 

You could have a simple lookup table, where you map content type name with a type or processor type directly.

**Comment by jtonvang** [comment]
> If I understand you correctly, you could implement this in `IContentApiModelFilter`. You can access the content type from `ContentApiModel.ContentType.First()` and then determine which "processor" to run. The name "filter" doesn't imply that you can only remove things, think of it as filters in MVC, I guess this would be the most equivalent https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0#result-filters.
> 
> You could have a simple lookup table, where you map content type name with a type or processor type directly.

Thanks a lot, that helps! I'll give it a go :) 🥇

**Comment by JohanPetersson** [comment]
Just let us know if the API isn't sufficient for your needs and if it works, please close this ticket.
