### ISSUE TITLE
Reset pagetype / remove properties no longer in code (1.0.0-inte-020002)

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#28]
When removing a property from code it can not be deleted from the page type i admin. The "From Code" column is not there any more so it's no way to see that the property is missing in code. I guess this property will stay alive since it got values from before it was removed from code. 

![image](https://user-images.githubusercontent.com/106393/114033145-4885e300-987d-11eb-9378-1544e1e3f0c1.png)

**Comment by barteksekula** [comment]
You're right.
