### ISSUE TITLE
AllowedTypes for content areas, more user friendly approach

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#31]
Today when we set restrictions on a content area you get the message "You can add these content types block, block". The name of the block or even better show the **display name**  to the editor.  The same behaviour is in the .Net version of Episerver but since .Net core will be better, this will increase the editor experience.

[AllowedTypes(new[] { typeof(SynonymBlock), typeof(InspirationSynonymBlock) })]

![image](https://user-images.githubusercontent.com/106393/114736776-aff0d680-9d46-11eb-8b1c-3283bdd1fb3a.png)

@barteksekula

**Comment by lunchin** [comment]
This feature is being implemented and will be in future release after GA
