### ISSUE TITLE
Async support in Scheduled Jobs

### ISSUE THREAD

**Issue by marisks** [episerver/netcore-preview#59]
Are there any plans to support async in the Scheduled Jobs? Now we have to override the sync version of the Execute method.
Sometimes we have to call async APIs from the Scheduled Jobs and in .NET Core, it is not that easy to call those from the sync context and in most cases ends in deadlocks.

**Comment by lunchin** [comment]
We plan to get to this and more async apis in the next major.  Trying to make the upgrade as easy as possible right now.
