### ISSUE TITLE
UnknownImageFormatException: Image cannot be loaded. Available decoders: - PNG : PngDecoder - TGA : TgaDecoder - BMP : BmpDecoder - JPEG : JpegDecoder - GIF : GifDecoder

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#60]
Having a svg image data model like this editors are able to upload svg files and preview then i asset pane. 

 [ContentType(DisplayName = "VectorImageFile", GUID = "c0b70fd0-0d5b-4c53-83fe-e32ea8faa2d5")]
    [MediaDescriptor(ExtensionString = "svg")]
    public class VectorImageFile : ImageData
    {
        /// <summary>
        /// Gets the generated thumbnail for this media.
        /// </summary>
        public override Blob Thumbnail => BinaryData;
    }

But when using svg files in a content reference like this

[UIHint(UIHint.Image)]
        [Display(Name = "Footer Logo",
            Order = 10,
            GroupName = TabNames.FooterSettings)]
        [AllowedTypes(typeof(ImageData))]
        public virtual ContentReference FooterLogoReference { get; set; }

the preview functionality in Episerver breaks. See screenshots.

![image](https://user-images.githubusercontent.com/106393/118800887-b1ab3e00-b8a0-11eb-9dad-aaf27abfc78a.png)

![image](https://user-images.githubusercontent.com/106393/118800914-b7a11f00-b8a0-11eb-9fa5-f50ff06c7ac9.png)

Url that breaks:
https://localhost:44376/EPiServer/CMS/Thumbnail/Generate/?contentLink=68&epi.preventCache=1621421012051

```
<PackageReference Include="EPiServer.CMS.AspNetCore.Templating" Version="12.0.0-inte-020304" />
<PackageReference Include="EPiServer.CMS.Core" Version="12.0.0-inte-020304" />
<PackageReference Include="EPiServer.CMS.UI.Core" Version="12.0.0-inte-020863" />
```

@barteksekula

**Comment by oyvindwh** [comment]
Any news on this one @balanikas / @bjuris ? For editors it looks like the image is missing.

We are running on the latest nuget packages => Episerver.CMS.UI.Core 12.0.1.pre-022064

**Comment by bjuris** [comment]
@barteksekula is probably better off commenting since he fixed this issue on CMS 11, there is a bug on the backlog that have been scheduled to be adressed after GA.

**Comment by oyvindwh** [comment]
Will the 500 errors in the log for generating thumbs also be solved when fixing this @barteksekula ?

/EPiServer/CMS/Thumbnail/Generate/?contentLink=12&epi.preventCache=1633499287941

![image](https://user-images.githubusercontent.com/106393/136148483-57658daf-7e71-43fc-a5f1-3a858ca5f99a.png)

**Comment by barteksekula** [comment]
@oyvindwh yes
