### ISSUE TITLE
CMS editor crashes before loading (white screen)

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#79]
**Observations:**
On a site with CMS and Commerce installed, a user is member of the WebAdmins group (and no other groups). When the user logs in and goes to Episerver Edit UI, the page crashes on load. The sees only the global menu, while the editor interface is just a white workspace.

The whole Editor UI is unusable for the user.

While debugging the editor, I see that the Editor UI attempts to load two ClientResource files (CSS and JS) for the product picker widget. But these two requests are denied and redirected to an AccessDenied page (because the user is not a member of CommerceAdmins).

These are the ClientResource files that cannot be loaded:
- /EPiServer/EPiServer.Commerce.Shell/14.0.0.0/ClientResources/epi-ecf-ui/epiCommerce.css
- /EPiServer/EPiServer.Commerce.Shell/14.0.0.0/ClientResources/epi-ecf-ui/widgets.js

**Expected:**
When the user is not member of CommerceAdmin (or other relevant groups), the Editor UI should not attempt to load the product picker.

**Builds:**
- EPiServer.CMS.UI.Core: 12.0.0-inte-021292
- EPiServer.Commerce.Web: 14.0.0-inte-020696

**Comment by lunchin** [comment]
This has been fixed.  There is clientmodulepolicy for javascript files which defaults to editor policy
