### ISSUE TITLE
JS error when your plugin is not react

### ISSUE THREAD

**Issue by valdisiljuconoks** [episerver/netcore-preview#8]
```
index.ts:8 Uncaught TypeError: Cannot read property 'dataset' of null
    at Object.<anonymous> (index.ts:8)
    at n (bootstrap:19)
    at bootstrap:83
    at admin.bundle.js:1
```

![image](https://user-images.githubusercontent.com/1767179/108037752-b4e52280-7042-11eb-98b9-fd8f93a92599.png)

**Comment by lunchin** [comment]
Is there a reason you used the view instead of your own view?  Is it okay to close this?

**Comment by valdisiljuconoks** [comment]
Think we can close, cannot repro anymore
