### ISSUE TITLE
Request CurrentUICulture

### ISSUE THREAD

**Issue by valdisiljuconoks** [episerver/netcore-preview#82]
Hi folks,

I'm searching for a place in source code where CMS is setting culture info for the requested content language.
Whichever content language I'm browsing - always end up with `en-US` as `CultureInfo.CurrentUICulture`.

Can't seem to find any usage of `Microsoft.AspNetCore.Builder.RequestLocalizationOptions` or `Microsoft.AspNetCore.Localization.IRequestCultureProvider` in source code of CMS.

Any hints would be really appreciated!

I'm on `EPiServer.CMS" Version=12.0.0-pre-021534`.

**Comment by valdisiljuconoks** [comment]
I think there some issues with this. Basically below you can find code snippet in StartPage view template (cshtml).

```
<div>Current UI Culture - @CultureInfo.CurrentUICulture</div>
<div>Thread.CurrentUICulture - @Thread.CurrentThread.CurrentUICulture</div>
<div>IRequestCultureFeature.UICulture - @(Context.Features.Get<IRequestCultureFeature>().RequestCulture.UICulture)</div>
<div>IUserInterfaceLanguageAccessor.Language - @UserInterfaceLanguage.Language</div>
```

This is result of browsing `no` culture page:

![image](https://user-images.githubusercontent.com/1767179/124311422-6611d280-db76-11eb-9bdd-143ee014b4ac.png)

I think that there might be many 3rd party addons / libraries that relies on assumption that `CurrentUICulture` is the one that user has requested and sees result rendered in.

Or at least in example here - I would assume that resolution for the language should already happen up in the pipeline..

**Comment by valdisiljuconoks** [comment]
@jbearfoot any more comments on this issue (it's blocking publishing of the pre-release version of one of the packages)? :)

**Comment by jbearfoot** [comment]
Hi, sorry for late reply, I have been away on vacation. I will take a look tomorrow and see if I can find a good place where we can assign CurrentUICulture (a middleware between routing and endpoint execution would be ideal, but it feels overkill with a custom middleware for just that)

**Comment by jbearfoot** [comment]
There is now a PR up where I have fixed so Thread cultures are assigned. I have also implemented a request culture provider so if partner call .AddRequestLocalization() they will automatically get the provider (CMS adds the provider to options, so no need for partner to do that).
There is however no one else in my team working this week, so it might take some time until the PR gets merged (if accepted), so hopefully it will be in 12.0.2 release.

**Comment by valdisiljuconoks** [comment]
Awesome! Thanks!

**Comment by jbearfoot** [comment]
This has now been merged and is available in the 12.0.2-pre- packages, don't think they are uploaded to the feed yet though.

**Comment by valdisiljuconoks** [comment]
thx for heads-up

**Comment by tholee** [comment]
@jbearfoot you said that: "After a content has been routed to and the language for the request have been determined the routing api will call IUpdateCurrentLanguage.SetRoutedContent with the content routed to and the language the request was determined to. "

Does that mean that plain (non Optimizely content) controllers cannot rely og e.g. ```ContentLanguage.PreferredCulture``` anymore as was the case in previous versions? It seems a bit inconsistent.

With the shown host names and by navigating to http://localhost:4001/foo gives debugger result as below.
```
public class FooController : ControllerBase
{
    [Route("foo")]
    public IActionResult Index()
    {
        var host = SiteDefinition.Current.GetHost(Request.Host.Value, fallbackToWildcard: true);
        var preferredCulture = ContentLanguage.PreferredCulture;
        return Content($"Language from host: {host.Language.Name} and from PreferredCulture:{preferredCulture}");
    }
}
```
![image](https://user-images.githubusercontent.com/1217446/132851178-353b78f7-cacc-4095-a492-6355e222b32b.png)
![image](https://user-images.githubusercontent.com/1217446/132851408-16696419-489b-4021-a497-16486ee84a55.png)

**Comment by jbearfoot** [comment]
I guess one can argue if the old behavior where ContentLanguage.PrefferedCulture was set even for request that was not for content was correct.... My thought was that the old behavior was not correct (perhaps not that much that we set ContentLanguage.PrefferedCulture but more that we set Thread.CurrentCulture and Thread.CurrentUICulture). If it turns out that many misses that we can certainly add that behavior back, it would not be a big change.
Anyway, you could implement the cms11 behaviour your self. First you could implement a RequestLocalizationProvider like:
 ` public class NonContentCultureProvider : RequestCultureProvider
    {
        private readonly IUrlResolver _urlResolver;
        private readonly IContentLanguageAccessor _contentLanguageAccessor;

        public NonContentCultureProvider(IUrlResolver urlResolver, IContentLanguageAccessor contentLanguageAccessor)
        {
            _urlResolver = urlResolver;
            _contentLanguageAccessor = contentLanguageAccessor;
        }

        public override Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext)
        {
            //This provider only sets culture for non-content requests
            if (httpContext.Features.Get<IContentRouteFeature>() is null)
            {
                //The router will not match to a content but it will resolve language
                var resolvedContent = _urlResolver.Route(new UrlBuilder(httpContext.Request.GetEncodedUrl()),
                   new RouteArguments
                   {
                       ExactMatch = false,
                       MatchWildcardHost = true
                   });

                var language = resolvedContent.MatchedHost?.Language?.Name ?? resolvedContent?.RouteLanguage;
                if (!string.IsNullOrEmpty(language))
                {
                    _contentLanguageAccessor.Language = CultureInfo.GetCultureInfo(language);
                    return Task<ProviderCultureResult>.FromResult(new ProviderCultureResult(language));
                }
            }
           
            return NullProviderCultureResult;
        }`

Then you could register the provider in startup like:
  app.UseRequestLocalization(o =>
            {
                o.RequestCultureProviders.Insert(0, new NonContentCultureProvider(
                    app.ApplicationServices.GetRequiredService<IUrlResolver>(),
                    app.ApplicationServices.GetRequiredService<IContentLanguageAccessor>()));
                o.AddSupportedCultures("en", "sv", "no");
            });
