### ISSUE TITLE
Is there a limit of blobs in one folder?

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#83]
We upload 614 small json files (total 750 kb) to a folder in the assets pane. Files get's imported (visible in Access Rights in Admin) but Assets pane can not show then due to an error. 

![image](https://user-images.githubusercontent.com/106393/121866881-a7ddf480-ccff-11eb-8730-10a430ab4172.png)

@barteksekula

**Comment by lunchin** [comment]
think this is fixed
