### ISSUE TITLE
Scheduled Jobs - History Messages should break

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#86]
If the messages do not break / line wrap you need to go into the Developer Toolbar to see the complete error message.

Allowing html (ex. `<br>`) in the result message would also be nice since we have that in the exiting .Net Framework version of Episerver.

![image](https://user-images.githubusercontent.com/106393/121897272-7b879f80-cd22-11eb-9024-1868e9dfe179.png)

@barteksekula

**Comment by lunchin** [comment]
Fixed in EPiServer.CMS.UI.Admin.12.0.1-pre-022064
