### ISSUE TITLE
Adding action name to VirtualPathArguments.Action has no effect

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#88]
**Observations:**
When resolving a URL to a content item, and adding a custom action name to VirtualPathArguments.Action, when resolving, the URL is the same as if it was not passed.

**Expected:**
The resolved URL should end with the custom action name.

**Builds:**
- EPiServer.CMS.UI.Core: 12.0.0-inte-021292
- EPiServer.Commerce.Web: 14.0.0-inte-020696

**Comment by valdisiljuconoks** [comment]
aha, that makes sense. thx for insights. this is one of the slippery stone to step on ;)

**Comment by jbearfoot** [comment]
Hmm, perhaps should not have let VirtualPathArguments inherit UrlResolverArguments, it made sense from a performance perspective to avoid allocating new objects and copy values but then it opened up for this not so obvious side effect...
