### ISSUE TITLE
Adding query string parameters to UrlResolverArguments.RouteValues has no effect

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#94]
**Observations:**
When resolving a URL to a content item, and adding custom query string parameters (as route values) to UrlResolverArguments.RouteValues, the URL is the same as if it was not passed.

**Expected:**
The resolved URL should end with query string parameters, reflecting the passed route values.

**Builds:**
- EPiServer.CMS.UI.Core: 12.0.0-inte-021292
- EPiServer.Commerce.Web: 14.0.0-inte-020696

**Comment by stefanolsen** [comment]
It looks like it works when calling `GetUrl(UrlBuilder urlBuilderWithInternalUrl, UrlResolverArguments arguments)`, but not `GetUrl(ContentReference contentLink, string language, UrlResolverArguments arguments)`.

Checked the code. The first overload has query string handling, while the second does not.

I would prefer that these two overloads behaves in the same way.

**Comment by stefanolsen** [comment]
@jbearfoot: Can you check whether the above is easy to fix?

**Comment by jbearfoot** [comment]
There is currently a PR up that includes a fix for this. So it will be fixed but not sure when there will be a package available that includes the fix

**Comment by stefanolsen** [comment]
@jbearfoot: Very nice. Will you be writing release notes for future releases, so we can see which issues to re-test after a release?

**Comment by jbearfoot** [comment]
It will be part of EPiServer.CMS.Core 12.0.2 package
