### ISSUE TITLE
Language version for page shows translated versions of page which is not enabled in admin

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#95]
Should this list also include translated versions when we have disabled these languages? Yes, a version do exits on no-no2 and yes we can delete it, but if we disable the language in admin and disable the language in Language Settings I suggest that the translated version does not show in this list.

@barteksekula 

![image](https://user-images.githubusercontent.com/106393/123242304-2d248e80-d4e2-11eb-8a3a-9790eeab6a28.png)

**Comment by barteksekula** [comment]
@oyvindwh it always worked like that. We show all languages but when you try to access a version of disabled language you will see this message 
![image](https://user-images.githubusercontent.com/1321664/124317507-927a1e80-db77-11eb-81bd-b07d65731924.png)
and the form would be readonly.

**Comment by barteksekula** [comment]
Yes, those are sorted by date. This also hasn't changed during the conversion.

**Comment by lunchin** [comment]
Closing this as is same behavior.
