### ISSUE TITLE
Episerver Admin, manage websites / edit websites hangs on loading the page tree structure

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#96]
When working with websites in Episerver (in admin mode) loading the page tree structure takes "forever" if you have many pages in the tree structure. There is no indicator showing that tree is loading, no interactions can be done while waiting (ex delete or edit a host name). Looks like the complete structure is loaded.

![image](https://user-images.githubusercontent.com/106393/123587833-27cb8a80-d7e7-11eb-9dad-719e888a9423.png)

@barteksekula, you have access to the integration environment and test it there.

**Comment by oyvindwh** [comment]
And same with export content images

![image](https://user-images.githubusercontent.com/106393/124581339-4ff36300-de51-11eb-876f-bed8ff636358.png)

@barteksekula

**Comment by lunchin** [comment]
Fixed in EPiServer.CMS.UI.Admin.12.0.1-pre-022064
