### ISSUE TITLE
Unknow exception when opening av page tree structure in Episerver 

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#97]
Sub pages contains both Arabic and Chinese translated pages.

![image](https://user-images.githubusercontent.com/106393/123588517-2b134600-d7e8-11eb-9ad2-00b01b6e6b81.png)

@barteksekula, can be seen in the integration environment. **More details can be shared in Teams.**

@lunchin

**Comment by barteksekula** [comment]
Microsoft fixed it as part of aspnetcore6 https://github.com/dotnet/aspnetcore/commit/0b8a066f58d63e6a8a37b073c308b30b2a60cd49

in aspnetcore5 they only allowed to control the Input threshhold:
https://github.com/dotnet/aspnetcore/blob/v5.0.9/src/Mvc/Mvc.NewtonsoftJson/src/MvcNewtonsoftJsonOptions.cs#L50

in aspnetcore6 we can also control the output:
https://github.com/dotnet/aspnetcore/blob/v6.0.0-preview.7.21378.6/src/Mvc/Mvc.NewtonsoftJson/src/MvcNewtonsoftJsonOptions.cs#L70

For now (until we are on aspnetcore5) customers that use newtonsoft will have to use this workaround for our stores:
```cs
var uiOptions = context.RequestServices.GetService<UIOptions>(); 
var resolver = context.RequestServices.GetService<IVirtualPathResolver>();
var syncIoFeature = context.Features.Get<IHttpBodyControlFeature>();
app.Use(async (context, next) =>
{
    var uiEditUrl = resolver.ToAbsolute(uiOptions.EditUrl.ToString()).TrimEnd('/');
    if (context.Request.Path.StartsWithSegments(uiEditUrl, StringComparison.OrdinalIgnoreCase))
    {        
        if (syncIoFeature != null)
        {
            syncIoFeature.AllowSynchronousIO = true;
        }
    }
    await next();
});
```
