### ISSUE TITLE
Routing issue when startpage has "shortcut to another content item" set up. Expects 404, get's 301

### ISSUE THREAD

**Issue by oyvindwh** [episerver/netcore-preview#98]
When setting up a shortcut from the startpage to a sub page 404's will be handled as 301 and redirected to the content item.  The expected behaviour would be a 404.  
![image](https://user-images.githubusercontent.com/106393/124135581-3a162480-da84-11eb-8168-de885ee1a1d1.png)

This is also a performance issue, since in my case we have 20+ language without flags that normally would give 404, but now get's redirected to the startpage.
![image](https://user-images.githubusercontent.com/106393/124136574-31721e00-da85-11eb-969a-a04d3c15f92c.png)

Reproduce:
Install Alloy
On Startpage set "Shortcut to another content item" to About us.
In browser use url https://localhost:44333/doesnotexists (returns 301 and redirect)
In browser use url https://localhost:44333/en/about-us/doesnot (returns 404)

@jbearfoot

**Comment by shahramshahram** [comment]
Thanks for reporting the issue, I have added to our internal issue tracker.

**Comment by lunchin** [comment]
Fixed in EPiServer.CMS.AspNetCore.Routing.12.0.1
